[master]: prefix should exists at env var

diff --git a/bin/git-pwd b/bin/git-pwd
--- a/bin/git-pwd
+++ b/bin/git-pwd
@@ -6,9 +6,14 @@ JIRA_CODE=`echo $GIT_BRANCH | sed -e 's/_[a-z0-9_]*//'`
 echo Branch: $GIT_BRANCH
 if [ "$GIT_BRANCH" == "$JIRA_CODE" ]
 then
-    echo "Error:  cannot detect jira issue code!"
-else
-    echo "Issue:  https://jira.badoojira.com/browse/$JIRA_CODE"
+    echo >&2 "Error:  cannot detect jira issue code!"
+    exit
 fi
 
+if [[ "" == "${JIRA_URL_PREFIX}" ]]; then
+    echo >&2 "Please define JIRA_URL_PREFIX env var"
+    exit
+fi
+
+echo "Issue:  ${JIRA_URL_PREFIX}${JIRA_CODE}"
 echo
