[master]: Proper error texts for git pwd

diff --git a/bin/git-pwd b/bin/git-pwd
--- a/bin/git-pwd
+++ b/bin/git-pwd
@@ -6,12 +6,12 @@ JIRA_CODE=`echo $GIT_BRANCH | sed -e 's/_[a-z0-9_]*//'`
 echo Branch: $GIT_BRANCH
 if [ "$GIT_BRANCH" == "$JIRA_CODE" ]
 then
-    echo >&2 "Error:  cannot detect jira issue code!"
+    >&2 echo "Error:  cannot detect jira issue code!"
     exit
 fi
 
 if [[ "" == "${JIRA_URL_PREFIX}" ]]; then
-    echo >&2 "Please define JIRA_URL_PREFIX env var"
+    >&2 echo "Please define JIRA_URL_PREFIX env var"
     exit
 fi
 
